[theme]
primaryColor="#007DFF"
backgroundColor="#0E1117"
secondaryBackgroundColor="#262730"
textColor="#FAFAFA"
font="sans serif"
[server]
port=8501
headless=true
[browser]
gatherUsageStats = false
[global]
developmentMode = false
